server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-57c08-100108837-3fa9fa0442ab.kr.lb.naverncp.com:8888"