spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web.reactive: TRACE

