spring:
  application:
    name: user-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
---
spring:
  application:
    name: user-service
  profiles:
    active: prod
  config:
    import: optional:configserver:http://223.130.131.65:8888