spring:
  application:
    name: chat-service
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-57c08-100108837-3fa9fa0442ab.kr.lb.naverncp.com:8888"